### ISSUE TITLE
leaks

### ISSUE THREAD

**Issue by mlen** [tomekwojcik/SSHFS-Manager#2]
AppController.m:291:2 leak of an object allocated on line 272 // leaked NSTask + some extra objects it requires
AppController.m:407:4 leak of an object allocated on line 385 // same here

I'll try to fix these leaks later today or maybe tomorrow.

**Comment by tomekwojcik** [comment]
OK. I'll take a look at that, too.

**Comment by mlen** [comment]
I think we should have a look at NSTask chapter in Cocoa programming.

**Comment by tomekwojcik** [comment]
It looks like I fixed the leaks. Instruments show no leaked objects. If you could run the app through code analyzer I'd be grateful.

**Comment by mlen** [comment]
No leaks found. Great job.

**Comment by tomekwojcik** [comment]
Great :).
